config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :beer_taps do
      put "toggle-cleaning" => "beer_taps#toggle_cleaning"
    end

    resources :kegs do
      resources :pours, only: [:index, :destroy]

      get "tap" => "kegs#list_taps"
      put "tap" => "kegs#tap_keg"
      delete "tap" => "kegs#untap_keg"

      get :clone
    end
    resources :temperature_sensors, except: [:new, :create] do
      collection do
        get "all_graphs"
      end
    end

    resources :users

    get "settings" => "settings#index"
    get "achievements" => "metrics#achievements"
  end

  namespace :api do
    namespace :v1 do
      resources :auth, only: [:create]
      resources :taps, only: [:index], controller: "beer_taps"
      resources :kegs, only: [:index, :show]
      resources :pours, only: [:index, :show, :create]
      resources :users, only: [:index, :show, :create] do
        resources :stats, only: [:index]
      end

      namespace :webhooks do
        resource :optix, only: :create
      end
    end
  end

  get "admin" => "admin/dashboards#show"

  resources :kegs
  resources :pours do
    get "volume" => "pours#volume"
  end
  resources :users

  get "activity/recent(/:limit)(.:format)" => "activity#recent", :as => "recent_activity"
  get "activity/user/:user_id(/:limit)(.:format)" => "activity#user_recent", :as => "user_activity"

  get "temperature_sensors/:sensor_id/:duration/:start_timestamp.:format" => "temperature_sensors#readings", :as => "temperature_sensor_readings"

  root to: "homepage#index"
end

app/models/keg.rb
class Keg < ApplicationRecord
  # Capacity is stored in fluid ounces
  KEG_CAPACITIES = [
    ["1/2 Barrel", 1980],
    ["1/4 Barrel", 984],
    ["1/6 Barrel", 636],
    ["Home Brew", 635]
  ]

  belongs_to :beer_tap, optional: true

  has_many :pours, inverse_of: :keg, dependent: :nullify
  has_one :active_pour, lambda { where(finished_at: nil) }, class_name: "Pour", inverse_of: :keg, dependent: nil

  validates :srm, numericality: {greater_than: 0, less_than: 41, allow_blank: true}

  def display_name
    [name, brewery].compact_blank.join(" by ")
  end

  def completed_pours
    pours.where.not(finished_at: nil)
  end

  def poured
    @poured ||= completed_pours.sum(:volume)
  end

  def poured_percent
    @poured_percent ||= (completed_pours.sum(:volume) / capacity) * 100
  end

  def remaining
    capacity - poured
  end

  def srm_rgb
    I18n.t!("srm.#{srm.to_i}")
  rescue
    nil
  end

  def start_pour(user = User.guest)
    pour = active_pour || pours.new
    pour.user = user if user
    pour.save!
    beer_tap.activate
    pour
  end

  def tap_it(tap_id)
    if tap_id.blank?
      errors.add(:beer_tap_id, "needs to be seleced")
      return
    end

    self.beer_tap_id = tap_id
    self.started_at ||= Time.current
    self.finished_at = nil
    self.active = true
    save # standard:disable Rails/SaveBang
  end

  def untap_it
    self.finished_at = Time.current
    self.active = false
    save # standard:disable Rails/SaveBang
  end

  def temp_data
    sensor = beer_tap.temperature_sensor
    if sensor
      sensor.temp_data
    else
      []
    end
  end

  def top_consumers
    pours.select("name, sum(volume) as total, count(pours.id) as count, avg(volume) as average, max(volume) as max").group("users.name").order("total desc").joins(:user)
  end

  def projected_empty
    if poured == 0 || remaining == 0
      "No projection available"
    else
      now = Time.current
      now + (now - started_at) / poured * remaining
    end
  end

  def days_on_tap
    return 0 unless started_at
    (((finished_at || Time.current) - started_at) / 1.day).round
  end
end

app/controllers/admin/kegs_controller.rb
class Admin::KegsController < Admin::ApplicationController
  def index
    @kegs = Keg.order("started_at DESC NULLS FIRST")
  end

  def show
    @keg = Keg.find(params[:id])
  end

  def new
    @keg = Keg.new
  end

  def create
    @keg = Keg.new(keg_params)
    if @keg.save
      redirect_to [:admin, @keg]
    else
      render :new
    end
  end

  def edit
    @keg = Keg.find(params[:id])
  end

  def update
    @keg = Keg.find(params[:id])
    if @keg.update(keg_params)
      redirect_to [:admin, @keg]
    else
      render :edit
    end
  end

  def clone
    @keg = Keg.find(params[:keg_id]).dup
    render :new
  end

  def list_taps
    @keg = Keg.find(params[:keg_id])
    @beer_taps = BeerTap.unused.order(:display_order).for_select
  end

  def tap_keg
    @keg = Keg.find(params[:keg_id])
    if @keg.tap_it(params[:keg].try(:[], :beer_tap_id))
      redirect_to [:admin, @keg]
    else
      @beer_taps = BeerTap.for_select
      render :list_taps
    end
  end

  def untap_keg
    @keg = Keg.find(params[:keg_id])
    @keg.untap_it
    redirect_to [:admin, @keg]
  end

  protected

  def keg_params
    params.require(:keg).permit(:name, :description, :capacity, :brewery, :style, :abv, :srm)
  end
end

app/controllers/api/v1/kegs_controller.rb
module API
  module V1
    class KegsController < ApplicationController
      def index
        @kegs = Keg.order("started_at DESC NULLS FIRST")
        @kegs = @kegs.where(active: true) if params[:active] == "true"
        render json: @kegs.preload(:beer_tap)
      end

      def show
        @keg = Keg.find(params[:id])
        render json: @keg
      end
    end
  end
end

app/controllers/kegs_controller.rb
class KegsController < ApplicationController
  def index
    @kegs = Keg.order("started_at DESC NULLS FIRST")
    @kegs = @kegs.where(active: true) if params[:active] == "true"
  end

  def show
    @keg = Keg.find(params[:id])
  end
end

app/views/admin/kegs/_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :brewery %>
<%= f.text_field :brewery %>

<%= f.label :style %>
<%= f.text_field :style %>

<%= f.label :abv %>
<%= f.number_field :abv, step: 0.1 %>

<%= f.label :srm %>
<%= f.number_field :srm %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.label :capacity %>
<%= f.select :capacity, Keg::KEG_CAPACITIES, :include_blank => true %>

app/views/admin/kegs/edit.html.erb
<div class="page-header">
  <h1>Edit Keg: <%= @keg.name %></h1>
</div>

<%= errors_for(@keg) %>

<%= form_for [:admin, @keg] do |f| %>
  <%= render 'form', {f: f} %>

  <div class="form-actions">
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', [:admin, @keg], :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/kegs/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New', new_admin_keg_path, :class => 'btn btn-default' %>
  </div>
  <h1>Admin Kegs</h1>
</div>

<table class="table-striped full-width">
  <thead>
    <tr>
      <th>Name</th>
      <th class="center">Tapped</th>
      <th class="center">Finished</th>
    </tr>
  </thead>
  <tbody>
    <% @kegs.each do |keg| %>
    <tr>
      <td><%= link_to keg.display_name, [:admin, keg] %></td>
      <td class="center"><%= l(keg.started_at, format: :norm) if keg.started_at %></td>
      <td class="center"><%= l(keg.finished_at, format: :norm) if keg.finished_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/kegs/list_taps.html.erb
<div class="page-header">
  <h1>Tap Keg: <%= @keg.name %></h1>
</div>

<%= errors_for(@keg) %>

<%= form_for @keg, url: admin_keg_tap_path(@keg), method: 'put' do |f| %>
  <%= f.label :beer_tap_id, 'What tap are we using?' %>
  <%= f.select :beer_tap_id, @beer_taps %>

  <div class="form-actions">
    <%= f.submit 'Tap that keg', :class => 'btn btn-primary' %>
    <%= link_to 'Never mind', [:admin, @keg], :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/kegs/new.html.erb
<div class="page-header">
  <h1>New Keg</h1>
</div>

<%= errors_for(@keg) %>

<%= form_for [:admin, @keg] do |f| %>
  <%= render 'form', {f: f} %>

  <div class="form-actions">
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', admin_kegs_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/kegs/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <% if @keg.active? %>
    <%= link_to 'Untap Keg', [:admin, @keg, :tap], method: :delete, class: 'btn btn-danger' %>
    <% else %>
    <%= link_to 'Tap Keg', [:admin, @keg, :tap], class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Edit', [:edit, :admin, @keg], class: 'btn btn-default' %>
    <%= link_to 'Clone', [:admin, @keg, :clone], class: 'btn btn-default' %>
  </div>
  <h1><%= link_to "Admin Kegs", [:admin, :kegs] %> > <%= @keg.display_name %></h1>
</div>

<h3>Stats</h3>
<table class="table-striped" id="stats">
  <tr>
    <td>Poured</td>
    <td class="poured"><%= @keg.poured.round %> oz</td>
  </tr>
  <tr>
    <td>Remaining</td>
    <td class="remaining"><%= @keg.remaining.round%> oz</td>
  </tr>
  <tr>
    <td>Pours</td>
    <td class="pours"><%= @keg.completed_pours.size %></td>
  </tr>
  <tr>
    <td>Average pour volume</td>
    <td class="average-pour-volume"><%= "%0.1f" % @keg.completed_pours.average(:volume).to_f %> oz</td>
  </tr>
  <% if @keg.completed_pours.any? && @keg.active? %>
  <tr>
    <td>Projected empty date</td>
    <td class="projected-empty-date"><%= @keg.projected_empty.strftime("%a, %b %d") %></td>
  </tr>
  <tr>
    <td>Days until empty</td>
    <td class="days-until-empty"><%= (@keg.projected_empty - Time.current).to_i / 1.day %></td>
  </tr>
  <% end %>
  <% if @keg.started_at %>
  <tr>
    <td>Started at</td>
    <td><%= l(@keg.started_at, format: :norm) %></td>
  </tr>
  <% end %>
  <% if @keg.finished_at %>
  <tr>
    <td>Finished at</td>
    <td><%= l(@keg.finished_at, format: :norm) %></td>
  </tr>
  <% end %>
  <% if @keg.started_at %>
  <tr>
    <td>Days on tap</td>
    <td><%= @keg.days_on_tap %></td>
  </tr>
  <% end %>
</table>

<h3>Recent Pours</h3>
<%= render 'admin/pours/table', pours: @keg.pours.for_listing.limit(15) %>

<%= link_to 'More', admin_keg_pours_path(@keg, page: 1), class: 'btn' if @keg.pours.for_listing.count > 15 %>