config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :beer_taps do
      put "toggle-cleaning" => "beer_taps#toggle_cleaning"
    end

    resources :kegs do
      resources :pours, only: [:index, :destroy]

      get "tap" => "kegs#list_taps"
      put "tap" => "kegs#tap_keg"
      delete "tap" => "kegs#untap_keg"

      get :clone
    end
    resources :temperature_sensors, except: [:new, :create] do
      collection do
        get "all_graphs"
      end
    end

    resources :users

    get "settings" => "settings#index"
    get "achievements" => "metrics#achievements"
  end

  namespace :api do
    namespace :v1 do
      resources :auth, only: [:create]
      resources :taps, only: [:index], controller: "beer_taps"
      resources :kegs, only: [:index, :show]
      resources :pours, only: [:index, :show, :create]
      resources :users, only: [:index, :show, :create] do
        resources :stats, only: [:index]
      end

      namespace :webhooks do
        resource :optix, only: :create
      end
    end
  end

  get "admin" => "admin/dashboards#show"

  resources :kegs
  resources :pours do
    get "volume" => "pours#volume"
  end
  resources :users

  get "activity/recent(/:limit)(.:format)" => "activity#recent", :as => "recent_activity"
  get "activity/user/:user_id(/:limit)(.:format)" => "activity#user_recent", :as => "user_activity"

  get "temperature_sensors/:sensor_id/:duration/:start_timestamp.:format" => "temperature_sensors#readings", :as => "temperature_sensor_readings"

  root to: "homepage#index"
end

app/models/pour.rb
# Sensor ticks is stored for calibration purposes only

# Volume is stored in fluid ounces
# however most sensors report as pulses per L
# Swissflow: between 5400 to 6100 pulses/L
# ml * 0.033814 = fl oz

class Pour < ApplicationRecord
  belongs_to :keg
  belongs_to :user

  before_save :calculate_duration
  after_save :set_last_pour_at

  scope :finished, lambda { where.not(finished_at: nil) }
  scope :non_guest, lambda { where("user_id > 0") }
  scope :for_listing, lambda { where.not(volume: nil).includes(:keg, :user).order("created_at desc") }
  scope :recent, lambda { where("created_at > ?", 30.days.ago) }

  def self.between_dates(start_time:, end_time:)
    start_time ||= 10.years.ago
    end_time ||= 10.years.from_now

    where(created_at: start_time..end_time)
  end

  def finish_pour(time)
    self.finished_at = time
    if sensor_ticks.to_i == 0
      keg.beer_tap.deactivate
      destroy!
    else
      save!
    end
  end

  def complete?
    finished_at.nil? ? false : (Time.current - finished_at) > Setting.pour_timeout
  end

  private

  def calculate_duration
    self.duration = finished_at - started_at if finished_at && started_at
  end

  def set_last_pour_at
    if finished_at && (user_id_changed? || finished_at_changed?)
      User.find(changes["user_id"] || [user_id]).each do |user|
        user.last_pour_at = user.pours.finished.maximum(:created_at)
        user.save!
      end
    end
  end
end

app/controllers/admin/pours_controller.rb
class Admin::PoursController < Admin::ApplicationController
  def index
    @keg = Keg.find(params[:keg_id])
    @pagy, @pours = pagy(@keg.pours.for_listing)
  end

  def destroy
    keg = Keg.find(params[:keg_id])
    pour = keg.pours.find(params[:id])
    pour.destroy!
    redirect_to :back
  end
end

app/controllers/api/v1/pours_controller.rb
module API
  module V1
    class PoursController < ApplicationController
      def index
        @pours = Pour.for_listing.except(:includes)
          .between_dates(start_time: start_time, end_time: end_time)

        render json: Oj.dump(@pours.as_json(except: [:sensor_ticks, :updated_at]), mode: :compat)
      end

      def show
        pours = Pour.between_dates(start_time: start_time, end_time: end_time)
        case params[:id]
        when "by_beer"
          data = pours.joins(:keg).where.not(started_at: nil)
            .group("kegs.name, pour_date").order("kegs.name, pour_date")
            .pluck(Arel.sql("kegs.name AS name, date_trunc('day', pours.started_at::TIMESTAMPTZ AT TIME ZONE '#{Time.zone.tzinfo.canonical_identifier}') AS pour_date, count(pours.id) AS pour_count"))
            .each.with_object({}) do |pour, out|
              (out[pour[0]] ||= []) << [pour[1].to_date, pour[2]]
            end

          render json: Oj.dump(data.as_json, mode: :compat)
        when "by_user"
          data = pours.joins(:user)
            .group("users.name, users.email").select("users.name", "users.email, SUM(pours.volume) AS volume")
          render json: Oj.dump(data.as_json, mode: :compat)
        end
      end

      def create
        user = User.where("id = ? OR rfid = ?", params[:user_id], params[:user_rfid]).first! if params[:user_id] != "0"
        unless user.pours_remaining?
          render status: :forbidden, plain: "Insufficient credits remaining"
          return
        end

        tap = BeerTap.find(params[:beer_tap_id])
        pour = tap.active_keg.start_pour(user)

        if pour.persisted?
          render json: Oj.dump(pour.as_json, mode: :compat), status: :created
        else
          render json: Oj.dump(pour.errors.to_json, mode: :compat), status: :unprocessible_entity
        end
      end

      private

      def start_time
        if params[:start_time]
          Time.zone.parse(params[:start_time])
        end
      end

      def end_time
        if params[:end_time]
          Time.zone.parse(params[:end_time])
        end
      end
    end
  end
end

app/controllers/pours_controller.rb
class PoursController < ApplicationController
  def index
    @pagy, @pours = pagy(Pour.for_listing)
  end

  def new
    @users = User.where.not(name: "Guest").order(:name)
  end

  def create
    user = User.where("id = ? OR rfid = ?", params[:user_id], params[:user_rfid]).first! if params[:user_id] != "0"
    unless user.pours_remaining?
      render status: :forbidden, plain: "Insufficient credits remaining"
      return
    end

    tap = BeerTap.find(params[:beer_tap_id])
    pour = tap.active_keg.start_pour(user)

    redirect_to pour
  end

  def show
    @pour = Pour.find(params[:id])
    redirect_to root_path if @pour.finished_at
  end

  def edit
    @pour = Pour.find(params[:id])
    @users = User.where.not(name: "Guest").order(:name)
  end

  def update
    pour = Pour.find(params[:id])
    if params.require(:pour).keys == ["finished_at"]
      pour.finish_pour(params[:pour][:finished_at])
    else
      pour.update!(pour_params)
    end
    redirect_to(params[:back_to] || root_path)
  end

  def volume
    @pour = Pour.find(params[:pour_id])
    output = @pour.volume ? "You have poured <span>#{"%0.2f" % @pour.volume} oz." : ""
    render text: output, layout: false
  end

  protected

  def pour_params
    params.require(:pour).permit(:user_id)
  end
end

app/helpers/pours_helper.rb
module PoursHelper
  def last_pour(user)
    pour_at = user.last_pour_at
    if pour_at
      "Last activity: #{I18n.l(pour_at, format: :norm)}"
    else
      "No activity yet"
    end
  end
end

app/views/pours/edit.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Return', :back, :class => 'btn btn-default' %>
  </div>
  <h1>Who are you?</h1>
</div>

<div class="user-list">
  <div class="row">
    <%= link_to 'New User', new_user_path %>
  </div>
  <% @users.each do |user| %>
  <div class="row">
    <%= link_to pour_path(@pour, pour: {user_id: user.id}, back_to: request.headers["Referer"]), method: 'put' do %>
      <%= image_tag user.gravatar_url(size: 100), alt: "#{user.name} Avatar", class: 'std-avatar' %>
      <div class="user-info">
        <div class="user-name"><%= user.name %></div>
        <div class="last-pour"><small><%= last_pour(user) %></small></div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/pours/index.html.erb
<table class="table-striped full-width">
  <thead>
    <tr>
      <th>Beer</th>
      <th>Volume</th>
      <th>Poured at</th>
      <th>User</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pours.each do |pour| %>
    <tr>
      <td><%= pour.keg.name %></td>
      <td><%= '%0.1f' % pour.volume %></td>
      <td><%= l(pour.started_at, format: :norm) %></td>
      <td><%= image_tag pour.user.gravatar_url(size: 50), alt: "#{pour.user.name} Avatar", class: 'mini-avatar' %> <%= pour.user.name %></td>
      <td>
        <%= link_to 'Claim pour', [:edit, pour] if pour.user_id == 0 %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_nav(@pagy) %>

app/views/pours/new.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Return', root_path, :class => 'btn btn-default' %>
  </div>
  <h1>Who are you?</h1>
</div>

<div class="user-list">
  <div class="row">
    <%= link_to 'New User', new_user_path %>
  </div>
  <div class="row">
    <input type="text" placeholder="Search" data-typeahead=".typeahead-list" data-typeahead-search=".user-name">
  </div>
  <div class="typeahead-list">
    <div class="row">
      <%= link_to pours_path(beer_tap_id: params[:beer_tap_id], user_id: 0), method: 'post' do %>
        <%= image_tag User.guest.gravatar_url(size: 100), alt: "Guest Avatar", class: 'std-avatar' %>
        <div class="user-info">
          <div class="user-name">Guest</div>
        </div>
      <% end %>
    </div>
    <% @users.each do |user| %>
    <div class="row">
      <%= link_to pours_path(beer_tap_id: params[:beer_tap_id], user_id: user.id), method: 'post' do %>
        <%= image_tag user.gravatar_url(size: 100), alt: "#{user.name} Avatar", class: 'std-avatar' %>
        <div class="user-info">
          <div class="user-name"><%= user.name %></div>
          <div class="last-pour"><small><%= last_pour(user) %></small></div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/pours/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Return', root_path, :class => 'btn btn-default' %>
  </div>
  <h1>Pour Started</h1>
</div>

<div id="in-progress-pour">
  <% if @pour.volume %>
  You have poured <span><%= '%0.2f' % @pour.volume %> oz.
  <% end %>
</div>

<%= link_to 'Finished', root_path, :class => 'btn btn-primary' %>

<script type="text/javascript" charset="utf-8">
$(function() {
  setInterval(function() {
    $.ajax({
      url: "<%= pour_volume_path(@pour)%>"
    }).success(function(data, status, xhr) {
      $('#in-progress-pour').html(data)
    })
  }, 500);
})
</script>