config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :beer_taps do
      put "toggle-cleaning" => "beer_taps#toggle_cleaning"
    end

    resources :kegs do
      resources :pours, only: [:index, :destroy]

      get "tap" => "kegs#list_taps"
      put "tap" => "kegs#tap_keg"
      delete "tap" => "kegs#untap_keg"

      get :clone
    end
    resources :temperature_sensors, except: [:new, :create] do
      collection do
        get "all_graphs"
      end
    end

    resources :users

    get "settings" => "settings#index"
    get "achievements" => "metrics#achievements"
  end

  namespace :api do
    namespace :v1 do
      resources :auth, only: [:create]
      resources :taps, only: [:index], controller: "beer_taps"
      resources :kegs, only: [:index, :show]
      resources :pours, only: [:index, :show, :create]
      resources :users, only: [:index, :show, :create] do
        resources :stats, only: [:index]
      end

      namespace :webhooks do
        resource :optix, only: :create
      end
    end
  end

  get "admin" => "admin/dashboards#show"

  resources :kegs
  resources :pours do
    get "volume" => "pours#volume"
  end
  resources :users

  get "activity/recent(/:limit)(.:format)" => "activity#recent", :as => "recent_activity"
  get "activity/user/:user_id(/:limit)(.:format)" => "activity#user_recent", :as => "user_activity"

  get "temperature_sensors/:sensor_id/:duration/:start_timestamp.:format" => "temperature_sensors#readings", :as => "temperature_sensor_readings"

  root to: "homepage#index"
end

app/models/temperature_sensor.rb
class TemperatureSensor < ApplicationRecord
  has_many :temperature_readings, dependent: :destroy
  has_one :latest_reading, lambda { order("created_at DESC") }, class_name: "TemperatureReading", inverse_of: false, dependent: nil
  has_one :kegerator, dependent: :nullify

  def self.for_select
    all.map { |tap| [tap.name, tap.id] }
  end

  def self.monitor
    loop do
      Temp.discover.each do |id, sensor|
        temp_sensor = where(code: id).first || create!(name: id, code: id)
        begin
          temp_sensor.temperature_readings.create!(temp_c: sensor.c)
        rescue Temp::ReadingFailed => e
          Rails.logger.debug { "Could not read temperature on #{id}\n#{e.message}" }
        end
      end

      sleep(60 - Time.current.sec)
    end
  end

  def sensor
    @sensor ||= Temp::Sensor.from_id(code)
  end

  def temp_data(start_time = 24.hours.ago, end_time = Time.current)
    temperature_readings
      .where(created_at: (start_time...end_time))
      .order(:created_at)
      .pluck(:temp_f, Arel.sql("extract(epoch from created_at)"))
  end
end

app/controllers/admin/temperature_sensors_controller.rb
class Admin::TemperatureSensorsController < Admin::ApplicationController
  def index
    @temperature_sensors = TemperatureSensor.order(:name)
  end

  def all_graphs
    @temperature_sensors = TemperatureSensor.order(:name)
  end

  def show
    @temperature_sensor = TemperatureSensor.find(params[:id])
  end

  def edit
    @temperature_sensor = TemperatureSensor.find(params[:id])
  end

  def update
    @temperature_sensor = TemperatureSensor.find(params[:id])
    if @temperature_sensor.update(temperature_sensor_params)
      redirect_to [:admin, @temperature_sensor]
    else
      render :edit
    end
  end

  protected

  def temperature_sensor_params
    params.require(:temperature_sensor).permit(:name)
  end
end

app/controllers/temperature_sensors_controller.rb
class TemperatureSensorsController < ApplicationController
  def readings
    expires_now

    sensor = TemperatureSensor.find(params[:sensor_id])
    start_time = Time.at(params[:start_timestamp].to_i).utc
    end_time = start_time + params[:duration].to_i

    render json: Oj.dump(sensor.temp_data(start_time, end_time))
  end
end

app/views/admin/temperature_sensors/all_graphs.html.erb
<div class="page-header">
  <h1>Admin > <%= link_to "Temperature Sensors", admin_temperature_sensors_path %> > All Graphs</h1>
</div>

<div class="all-graphs">
  <% @temperature_sensors.each do |sensor| %>
  <div class="row">
    <h3>
      <div data-sensor-id="<%= sensor.id %>" class="pull-right">
        <small class="when"><%= l(sensor.latest_reading.created_at, format: :norm) if sensor.latest_reading %></small>
        <span class="temperature"><%= '%0.1f' % sensor.latest_reading.temp_f if sensor.latest_reading %></span>&deg;F
      </div>
      <%= sensor.name %>
    </h3>
    <%= render "shared/temp_chart", sensor_id: sensor.id %>
  </div>
  <% end %>
</div>

app/views/admin/temperature_sensors/edit.html.erb
<div class="page-header">
  <h1>Edit Temperature Sensor: <%= @temperature_sensor.name %></h1>
</div>

<%= errors_for(@temperature_sensor) %>

<%= form_for [:admin, @temperature_sensor] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <div class="form-actions">
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', [:admin, @temperature_sensor], :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/temperature_sensors/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "All Graphs", all_graphs_admin_temperature_sensors_path, :class => 'btn btn-default' %>
  </div>
  <h1>Admin Tempterature Sensors</h1>
</div>

<table class="table-striped full-width">
  <thead>
    <tr>
      <th>Name</th>
      <th class="center">Hardware Code</th>
      <th class="center">Last Reading</th>
    </tr>
  </thead>
  <tbody>
    <% @temperature_sensors.each do |sensor| %>
    <tr>
      <td><%= link_to sensor.name, [:admin, sensor] %></td>
      <td class="center"><%= sensor.code %></td>
      <td class="center">
        <% if sensor.latest_reading %>
        <%= sensor.latest_reading.temp_f.round(1) %>F
        at <%= l(sensor.latest_reading.created_at, format: :norm) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/temperature_sensors/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', [:edit, :admin, @temperature_sensor], :class => 'btn btn-default' %>
  </div>
  <h1><%= link_to "Admin", admin_path %> > <%= link_to "Temperature Sensors", [:admin, :temperature_sensors] %> > <%= @temperature_sensor.name %></h1>
</div>

<table class="table-striped" id="stats">
  <tr>
    <td>Hardware Code</td>
    <td><%= @temperature_sensor.code %></td>
  </tr>
  <% if @temperature_sensor.latest_reading %>
  <tr>
    <td>Last reading</td>
    <td><%= @temperature_sensor.latest_reading.temp_f.round(1) %>F</td>
  </tr>
  <tr>
    <td>Last reading at</td>
    <td><%= l(@temperature_sensor.latest_reading.created_at, format: :norm) %></td>
  </tr>
  <% end %>
</table>

<div class="row">
  <%= render "shared/temp_chart", sensor_id: @temperature_sensor.id %>
</div>