config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :beer_taps do
      put "toggle-cleaning" => "beer_taps#toggle_cleaning"
    end

    resources :kegs do
      resources :pours, only: [:index, :destroy]

      get "tap" => "kegs#list_taps"
      put "tap" => "kegs#tap_keg"
      delete "tap" => "kegs#untap_keg"

      get :clone
    end
    resources :temperature_sensors, except: [:new, :create] do
      collection do
        get "all_graphs"
      end
    end

    resources :users

    get "settings" => "settings#index"
    get "achievements" => "metrics#achievements"
  end

  namespace :api do
    namespace :v1 do
      resources :auth, only: [:create]
      resources :taps, only: [:index], controller: "beer_taps"
      resources :kegs, only: [:index, :show]
      resources :pours, only: [:index, :show, :create]
      resources :users, only: [:index, :show, :create] do
        resources :stats, only: [:index]
      end

      namespace :webhooks do
        resource :optix, only: :create
      end
    end
  end

  get "admin" => "admin/dashboards#show"

  resources :kegs
  resources :pours do
    get "volume" => "pours#volume"
  end
  resources :users

  get "activity/recent(/:limit)(.:format)" => "activity#recent", :as => "recent_activity"
  get "activity/user/:user_id(/:limit)(.:format)" => "activity#user_recent", :as => "user_activity"

  get "temperature_sensors/:sensor_id/:duration/:start_timestamp.:format" => "temperature_sensors#readings", :as => "temperature_sensor_readings"

  root to: "homepage#index"
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < ApplicationController
    def show
    end
  end
end

app/views/admin/dashboards/show.html.erb
<div class="page-header">
  <div class="pull-right"><%= link_to 'Return', root_path, :class => 'btn btn-default' %></div>
  <h1>Admin</h1>
</div>

<ul>
  <li><%= link_to "Kegs", admin_kegs_path %></li>
  <li><%= link_to "Taps", admin_beer_taps_path %></li>
  <li><%= link_to "Temperature Sensors", admin_temperature_sensors_path %></li>
  <li><%= link_to "Users", admin_users_path %></li>
</ul>